= skeleton

Skeleton repository for template student guide and instructor guide
AsciiDoc files.

[IMPORTANT]
====
The skeleton repository is read-only for most team members.  If you want to
make changes raise an issue in GitHub.
====

== Branches
Commits to `master` branch are expected to build and may be immediately deployed to
ROLE stage without further notice.

Commits to `release/*` branches are expected to be final releases being sent to
production and may be immediately deployed to ROLE production and rendered as final
PDFs without further notice.  These branches are protected and will require approved
pull requests in order to be updated.

[cols="2*", options="header"]
|===
|branch
|purpose

|`devel`
|Current development

|`master`
|Latest release of skeleton. Immediately deploys to rol-stage.
|===

== Repository Structure
[cols="2*", options="header"]
|===
|file or directory
|purpose

|BUILD.adoc
|AsciiDoc file providing information about the build process

|README.adoc
|This file

|classroom/
|Directory containing classroom setup materials specific to this course

|guides/
|Directory containing template course materials

|slides/
|Course slide presentations
|===

[NOTE]
====
This document has been written using http://asciidoctor.org[AsciiDoc] markup.
A quick reference sheet is available at http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

GitHub will automatically render AsciiDoc files that end in `.adoc`, `.asciidoc`, or `.asc`.  For more
information, see https://github.com/github/markup.
====
